spring.application.name=login


# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://db.wtlbuscnqealkeqlhtgm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd!_DbS4R#2025
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none


